import { CardType, PokemonType, TrainerSubtype } from "./types"

// Generate a starter deck (Pikachu & Friends)
export function getStarterDeck() {
  return [
    // Pokémon Cards
    {
      id: "pika1",
      type: CardType.POKEMON,
      name: "Pikachu",
      hp: 60,
      stage: "Basic",
      pokemonType: PokemonType.LIGHTNING,
      weakness: PokemonType.FIGHTING,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Thunder Shock",
          damage: 10,
          energyCost: [PokemonType.LIGHTNING],
          effect: "Flip a coin. If heads, the Defending Pokémon is now Paralyzed.",
        },
        {
          name: "Quick Attack",
          damage: 20,
          energyCost: [PokemonType.COLORLESS, PokemonType.COLORLESS],
          effect: "Flip a coin. If heads, this attack does 10 more damage.",
        },
      ],
    },
    {
      id: "rai1",
      type: CardType.POKEMON,
      name: "Raichu",
      hp: 90,
      stage: "Stage 1",
      evolvesFrom: "Pikachu",
      pokemonType: PokemonType.LIGHTNING,
      weakness: PokemonType.FIGHTING,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Agility",
          damage: 20,
          energyCost: [PokemonType.LIGHTNING, PokemonType.COLORLESS],
          effect:
            "Flip a coin. If heads, during your opponent's next turn, prevent all effects of attacks, including damage, done to this Pokémon.",
        },
        {
          name: "Thunder",
          damage: 60,
          energyCost: [PokemonType.LIGHTNING, PokemonType.LIGHTNING, PokemonType.COLORLESS],
          effect: "This Pokémon does 10 damage to itself.",
        },
      ],
    },
    {
      id: "bulb1",
      type: CardType.POKEMON,
      name: "Bulbasaur",
      hp: 60,
      stage: "Basic",
      pokemonType: PokemonType.GRASS,
      weakness: PokemonType.FIRE,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Leech Seed",
          damage: 20,
          energyCost: [PokemonType.GRASS, PokemonType.COLORLESS],
          effect: "Remove 1 damage counter from this Pokémon.",
        },
      ],
    },
    {
      id: "ivy1",
      type: CardType.POKEMON,
      name: "Ivysaur",
      hp: 70,
      stage: "Stage 1",
      evolvesFrom: "Bulbasaur",
      pokemonType: PokemonType.GRASS,
      weakness: PokemonType.FIRE,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Vine Whip",
          damage: 30,
          energyCost: [PokemonType.GRASS, PokemonType.COLORLESS],
          effect: null,
        },
        {
          name: "Poisonpowder",
          damage: 20,
          energyCost: [PokemonType.GRASS, PokemonType.GRASS, PokemonType.COLORLESS],
          effect: "The Defending Pokémon is now Poisoned.",
        },
      ],
    },
    {
      id: "char1",
      type: CardType.POKEMON,
      name: "Charmander",
      hp: 50,
      stage: "Basic",
      pokemonType: PokemonType.FIRE,
      weakness: PokemonType.WATER,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Scratch",
          damage: 10,
          energyCost: [PokemonType.COLORLESS],
          effect: null,
        },
        {
          name: "Ember",
          damage: 30,
          energyCost: [PokemonType.FIRE, PokemonType.COLORLESS],
          effect: "Discard 1 Fire Energy card attached to this Pokémon.",
        },
      ],
    },
    {
      id: "squi1",
      type: CardType.POKEMON,
      name: "Squirtle",
      hp: 50,
      stage: "Basic",
      pokemonType: PokemonType.WATER,
      weakness: PokemonType.GRASS,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Bubble",
          damage: 10,
          energyCost: [PokemonType.WATER],
          effect: "Flip a coin. If heads, the Defending Pokémon is now Paralyzed.",
        },
        {
          name: "Withdraw",
          damage: 0,
          energyCost: [PokemonType.WATER, PokemonType.COLORLESS],
          effect: "During your opponent's next turn, prevent all damage done to this Pokémon by attacks.",
        },
      ],
    },
    {
      id: "pika2",
      type: CardType.POKEMON,
      name: "Pikachu",
      hp: 60,
      stage: "Basic",
      pokemonType: PokemonType.LIGHTNING,
      weakness: PokemonType.FIGHTING,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Thunder Shock",
          damage: 10,
          energyCost: [PokemonType.LIGHTNING],
          effect: "Flip a coin. If heads, the Defending Pokémon is now Paralyzed.",
        },
        {
          name: "Quick Attack",
          damage: 20,
          energyCost: [PokemonType.COLORLESS, PokemonType.COLORLESS],
          effect: "Flip a coin. If heads, this attack does 10 more damage.",
        },
      ],
    },
    {
      id: "bulb2",
      type: CardType.POKEMON,
      name: "Bulbasaur",
      hp: 60,
      stage: "Basic",
      pokemonType: PokemonType.GRASS,
      weakness: PokemonType.FIRE,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Leech Seed",
          damage: 20,
          energyCost: [PokemonType.GRASS, PokemonType.COLORLESS],
          effect: "Remove 1 damage counter from this Pokémon.",
        },
      ],
    },
    {
      id: "char2",
      type: CardType.POKEMON,
      name: "Charmander",
      hp: 50,
      stage: "Basic",
      pokemonType: PokemonType.FIRE,
      weakness: PokemonType.WATER,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Scratch",
          damage: 10,
          energyCost: [PokemonType.COLORLESS],
          effect: null,
        },
        {
          name: "Ember",
          damage: 30,
          energyCost: [PokemonType.FIRE, PokemonType.COLORLESS],
          effect: "Discard 1 Fire Energy card attached to this Pokémon.",
        },
      ],
    },
    {
      id: "squi2",
      type: CardType.POKEMON,
      name: "Squirtle",
      hp: 50,
      stage: "Basic",
      pokemonType: PokemonType.WATER,
      weakness: PokemonType.GRASS,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Bubble",
          damage: 10,
          energyCost: [PokemonType.WATER],
          effect: "Flip a coin. If heads, the Defending Pokémon is now Paralyzed.",
        },
        {
          name: "Withdraw",
          damage: 0,
          energyCost: [PokemonType.WATER, PokemonType.COLORLESS],
          effect: "During your opponent's next turn, prevent all damage done to this Pokémon by attacks.",
        },
      ],
    },

    // Trainer Cards
    {
      id: "prof1",
      type: CardType.TRAINER,
      name: "Professor Oak",
      subtype: TrainerSubtype.SUPPORTER,
      effect: "Discard your hand and draw 7 cards.",
    },
    {
      id: "potion1",
      type: CardType.TRAINER,
      name: "Potion",
      subtype: TrainerSubtype.ITEM,
      effect: "Remove 2 damage counters from 1 of your Pokémon.",
    },
    {
      id: "potion2",
      type: CardType.TRAINER,
      name: "Potion",
      subtype: TrainerSubtype.ITEM,
      effect: "Remove 2 damage counters from 1 of your Pokémon.",
    },
    {
      id: "switch1",
      type: CardType.TRAINER,
      name: "Switch",
      subtype: TrainerSubtype.ITEM,
      effect: "Switch your Active Pokémon with 1 of your Benched Pokémon.",
    },
    {
      id: "switch2",
      type: CardType.TRAINER,
      name: "Switch",
      subtype: TrainerSubtype.ITEM,
      effect: "Switch your Active Pokémon with 1 of your Benched Pokémon.",
    },
    {
      id: "energy1",
      type: CardType.TRAINER,
      name: "Energy Retrieval",
      subtype: TrainerSubtype.ITEM,
      effect: "Put 2 basic Energy cards from your discard pile into your hand.",
    },
    {
      id: "bill1",
      type: CardType.TRAINER,
      name: "Bill",
      subtype: TrainerSubtype.SUPPORTER,
      effect: "Draw 2 cards.",
    },
    {
      id: "bill2",
      type: CardType.TRAINER,
      name: "Bill",
      subtype: TrainerSubtype.SUPPORTER,
      effect: "Draw 2 cards.",
    },

    // Energy Cards
    {
      id: "lightning1",
      type: CardType.ENERGY,
      name: "Lightning Energy",
      energyType: PokemonType.LIGHTNING,
      provides: [PokemonType.LIGHTNING],
      special: false,
    },
    {
      id: "lightning2",
      type: CardType.ENERGY,
      name: "Lightning Energy",
      energyType: PokemonType.LIGHTNING,
      provides: [PokemonType.LIGHTNING],
      special: false,
    },
    {
      id: "lightning3",
      type: CardType.ENERGY,
      name: "Lightning Energy",
      energyType: PokemonType.LIGHTNING,
      provides: [PokemonType.LIGHTNING],
      special: false,
    },
    {
      id: "lightning4",
      type: CardType.ENERGY,
      name: "Lightning Energy",
      energyType: PokemonType.LIGHTNING,
      provides: [PokemonType.LIGHTNING],
      special: false,
    },
    {
      id: "lightning5",
      type: CardType.ENERGY,
      name: "Lightning Energy",
      energyType: PokemonType.LIGHTNING,
      provides: [PokemonType.LIGHTNING],
      special: false,
    },
    {
      id: "lightning6",
      type: CardType.ENERGY,
      name: "Lightning Energy",
      energyType: PokemonType.LIGHTNING,
      provides: [PokemonType.LIGHTNING],
      special: false,
    },
    {
      id: "grass1",
      type: CardType.ENERGY,
      name: "Grass Energy",
      energyType: PokemonType.GRASS,
      provides: [PokemonType.GRASS],
      special: false,
    },
    {
      id: "grass2",
      type: CardType.ENERGY,
      name: "Grass Energy",
      energyType: PokemonType.GRASS,
      provides: [PokemonType.GRASS],
      special: false,
    },
    {
      id: "grass3",
      type: CardType.ENERGY,
      name: "Grass Energy",
      energyType: PokemonType.GRASS,
      provides: [PokemonType.GRASS],
      special: false,
    },
    {
      id: "grass4",
      type: CardType.ENERGY,
      name: "Grass Energy",
      energyType: PokemonType.GRASS,
      provides: [PokemonType.GRASS],
      special: false,
    },
    {
      id: "fire1",
      type: CardType.ENERGY,
      name: "Fire Energy",
      energyType: PokemonType.FIRE,
      provides: [PokemonType.FIRE],
      special: false,
    },
    {
      id: "fire2",
      type: CardType.ENERGY,
      name: "Fire Energy",
      energyType: PokemonType.FIRE,
      provides: [PokemonType.FIRE],
      special: false,
    },
    {
      id: "fire3",
      type: CardType.ENERGY,
      name: "Fire Energy",
      energyType: PokemonType.FIRE,
      provides: [PokemonType.FIRE],
      special: false,
    },
    {
      id: "fire4",
      type: CardType.ENERGY,
      name: "Fire Energy",
      energyType: PokemonType.FIRE,
      provides: [PokemonType.FIRE],
      special: false,
    },
    {
      id: "water1",
      type: CardType.ENERGY,
      name: "Water Energy",
      energyType: PokemonType.WATER,
      provides: [PokemonType.WATER],
      special: false,
    },
    {
      id: "water2",
      type: CardType.ENERGY,
      name: "Water Energy",
      energyType: PokemonType.WATER,
      provides: [PokemonType.WATER],
      special: false,
    },
    {
      id: "water3",
      type: CardType.ENERGY,
      name: "Water Energy",
      energyType: PokemonType.WATER,
      provides: [PokemonType.WATER],
      special: false,
    },
    {
      id: "water4",
      type: CardType.ENERGY,
      name: "Water Energy",
      energyType: PokemonType.WATER,
      provides: [PokemonType.WATER],
      special: false,
    },
    {
      id: "double1",
      type: CardType.ENERGY,
      name: "Double Colorless Energy",
      energyType: PokemonType.COLORLESS,
      provides: [PokemonType.COLORLESS, PokemonType.COLORLESS],
      special: true,
    },
    {
      id: "double2",
      type: CardType.ENERGY,
      name: "Double Colorless Energy",
      energyType: PokemonType.COLORLESS,
      provides: [PokemonType.COLORLESS, PokemonType.COLORLESS],
      special: true,
    },
  ]
}

// Generate a water-focused deck
export function getWaterDeck() {
  return [
    // Pokémon Cards
    {
      id: "squi1",
      type: CardType.POKEMON,
      name: "Squirtle",
      hp: 50,
      stage: "Basic",
      pokemonType: PokemonType.WATER,
      weakness: PokemonType.GRASS,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Bubble",
          damage: 10,
          energyCost: [PokemonType.WATER],
          effect: "Flip a coin. If heads, the Defending Pokémon is now Paralyzed.",
        },
        {
          name: "Withdraw",
          damage: 0,
          energyCost: [PokemonType.WATER, PokemonType.COLORLESS],
          effect: "During your opponent's next turn, prevent all damage done to this Pokémon by attacks.",
        },
      ],
    },
    {
      id: "squi2",
      type: CardType.POKEMON,
      name: "Squirtle",
      hp: 50,
      stage: "Basic",
      pokemonType: PokemonType.WATER,
      weakness: PokemonType.GRASS,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Bubble",
          damage: 10,
          energyCost: [PokemonType.WATER],
          effect: "Flip a coin. If heads, the Defending Pokémon is now Paralyzed.",
        },
        {
          name: "Withdraw",
          damage: 0,
          energyCost: [PokemonType.WATER, PokemonType.COLORLESS],
          effect: "During your opponent's next turn, prevent all damage done to this Pokémon by attacks.",
        },
      ],
    },
    {
      id: "squi3",
      type: CardType.POKEMON,
      name: "Squirtle",
      hp: 50,
      stage: "Basic",
      pokemonType: PokemonType.WATER,
      weakness: PokemonType.GRASS,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Bubble",
          damage: 10,
          energyCost: [PokemonType.WATER],
          effect: "Flip a coin. If heads, the Defending Pokémon is now Paralyzed.",
        },
        {
          name: "Withdraw",
          damage: 0,
          energyCost: [PokemonType.WATER, PokemonType.COLORLESS],
          effect: "During your opponent's next turn, prevent all damage done to this Pokémon by attacks.",
        },
      ],
    },
    {
      id: "war1",
      type: CardType.POKEMON,
      name: "Wartortle",
      hp: 70,
      stage: "Stage 1",
      evolvesFrom: "Squirtle",
      pokemonType: PokemonType.WATER,
      weakness: PokemonType.GRASS,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Withdraw",
          damage: 0,
          energyCost: [PokemonType.WATER],
          effect: "During your opponent's next turn, prevent all damage done to this Pokémon by attacks.",
        },
        {
          name: "Water Gun",
          damage: 30,
          energyCost: [PokemonType.WATER, PokemonType.WATER, PokemonType.COLORLESS],
          effect: null,
        },
      ],
    },
    {
      id: "war2",
      type: CardType.POKEMON,
      name: "Wartortle",
      hp: 70,
      stage: "Stage 1",
      evolvesFrom: "Squirtle",
      pokemonType: PokemonType.WATER,
      weakness: PokemonType.GRASS,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Withdraw",
          damage: 0,
          energyCost: [PokemonType.WATER],
          effect: "During your opponent's next turn, prevent all damage done to this Pokémon by attacks.",
        },
        {
          name: "Water Gun",
          damage: 30,
          energyCost: [PokemonType.WATER, PokemonType.WATER, PokemonType.COLORLESS],
          effect: null,
        },
      ],
    },
    {
      id: "blas1",
      type: CardType.POKEMON,
      name: "Blastoise",
      hp: 100,
      stage: "Stage 2",
      evolvesFrom: "Wartortle",
      pokemonType: PokemonType.WATER,
      weakness: PokemonType.GRASS,
      resistance: null,
      retreatCost: 3,
      ability: {
        name: "Rain Dance",
        effect:
          "As often as you like during your turn, you may attach a Water Energy card from your hand to 1 of your Pokémon.",
      },
      attacks: [
        {
          name: "Hydro Pump",
          damage: 40,
          energyCost: [PokemonType.WATER, PokemonType.WATER, PokemonType.COLORLESS],
          effect:
            "Does 10 more damage for each Water Energy attached to this Pokémon but not used to pay for this attack's Energy cost.",
        },
      ],
    },
    {
      id: "star1",
      type: CardType.POKEMON,
      name: "Staryu",
      hp: 40,
      stage: "Basic",
      pokemonType: PokemonType.WATER,
      weakness: PokemonType.LIGHTNING,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Slap",
          damage: 20,
          energyCost: [PokemonType.WATER, PokemonType.COLORLESS],
          effect: null,
        },
      ],
    },
    {
      id: "star2",
      type: CardType.POKEMON,
      name: "Staryu",
      hp: 40,
      stage: "Basic",
      pokemonType: PokemonType.WATER,
      weakness: PokemonType.LIGHTNING,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Slap",
          damage: 20,
          energyCost: [PokemonType.WATER, PokemonType.COLORLESS],
          effect: null,
        },
      ],
    },
    {
      id: "star3",
      type: CardType.POKEMON,
      name: "Staryu",
      hp: 40,
      stage: "Basic",
      pokemonType: PokemonType.WATER,
      weakness: PokemonType.LIGHTNING,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Slap",
          damage: 20,
          energyCost: [PokemonType.WATER, PokemonType.COLORLESS],
          effect: null,
        },
      ],
    },
    {
      id: "starm1",
      type: CardType.POKEMON,
      name: "Starmie",
      hp: 60,
      stage: "Stage 1",
      evolvesFrom: "Staryu",
      pokemonType: PokemonType.WATER,
      weakness: PokemonType.LIGHTNING,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Star Freeze",
          damage: 20,
          energyCost: [PokemonType.WATER, PokemonType.COLORLESS],
          effect: "Flip a coin. If heads, the Defending Pokémon is now Paralyzed.",
        },
        {
          name: "Recover",
          damage: 0,
          energyCost: [PokemonType.WATER, PokemonType.WATER, PokemonType.COLORLESS],
          effect: "Discard 1 Water Energy card attached to this Pokémon. Remove all damage counters from this Pokémon.",
        },
      ],
    },
    {
      id: "starm2",
      type: CardType.POKEMON,
      name: "Starmie",
      hp: 60,
      stage: "Stage 1",
      evolvesFrom: "Staryu",
      pokemonType: PokemonType.WATER,
      weakness: PokemonType.LIGHTNING,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Star Freeze",
          damage: 20,
          energyCost: [PokemonType.WATER, PokemonType.COLORLESS],
          effect: "Flip a coin. If heads, the Defending Pokémon is now Paralyzed.",
        },
        {
          name: "Recover",
          damage: 0,
          energyCost: [PokemonType.WATER, PokemonType.WATER, PokemonType.COLORLESS],
          effect: "Discard 1 Water Energy card attached to this Pokémon. Remove all damage counters from this Pokémon.",
        },
      ],
    },

    // Trainer Cards
    {
      id: "prof1",
      type: CardType.TRAINER,
      name: "Professor Oak",
      subtype: TrainerSubtype.SUPPORTER,
      effect: "Discard your hand and draw 7 cards.",
    },
    {
      id: "prof2",
      type: CardType.TRAINER,
      name: "Professor Oak",
      subtype: TrainerSubtype.SUPPORTER,
      effect: "Discard your hand and draw 7 cards.",
    },
    {
      id: "bill1",
      type: CardType.TRAINER,
      name: "Bill",
      subtype: TrainerSubtype.SUPPORTER,
      effect: "Draw 2 cards.",
    },
    {
      id: "bill2",
      type: CardType.TRAINER,
      name: "Bill",
      subtype: TrainerSubtype.SUPPORTER,
      effect: "Draw 2 cards.",
    },
    {
      id: "bill3",
      type: CardType.TRAINER,
      name: "Bill",
      subtype: TrainerSubtype.SUPPORTER,
      effect: "Draw 2 cards.",
    },
    {
      id: "energy1",
      type: CardType.TRAINER,
      name: "Energy Retrieval",
      subtype: TrainerSubtype.ITEM,
      effect: "Put 2 basic Energy cards from your discard pile into your hand.",
    },
    {
      id: "energy2",
      type: CardType.TRAINER,
      name: "Energy Retrieval",
      subtype: TrainerSubtype.ITEM,
      effect: "Put 2 basic Energy cards from your discard pile into your hand.",
    },
    {
      id: "potion1",
      type: CardType.TRAINER,
      name: "Potion",
      subtype: TrainerSubtype.ITEM,
      effect: "Remove 2 damage counters from 1 of your Pokémon.",
    },
    {
      id: "potion2",
      type: CardType.TRAINER,
      name: "Potion",
      subtype: TrainerSubtype.ITEM,
      effect: "Remove 2 damage counters from 1 of your Pokémon.",
    },
    {
      id: "switch1",
      type: CardType.TRAINER,
      name: "Switch",
      subtype: TrainerSubtype.ITEM,
      effect: "Switch your Active Pokémon with 1 of your Benched Pokémon.",
    },
    {
      id: "switch2",
      type: CardType.TRAINER,
      name: "Switch",
      subtype: TrainerSubtype.ITEM,
      effect: "Switch your Active Pokémon with 1 of your Benched Pokémon.",
    },

    // Energy Cards
    {
      id: "water1",
      type: CardType.ENERGY,
      name: "Water Energy",
      energyType: PokemonType.WATER,
      provides: [PokemonType.WATER],
      special: false,
    },
    {
      id: "water2",
      type: CardType.ENERGY,
      name: "Water Energy",
      energyType: PokemonType.WATER,
      provides: [PokemonType.WATER],
      special: false,
    },
    {
      id: "water3",
      type: CardType.ENERGY,
      name: "Water Energy",
      energyType: PokemonType.WATER,
      provides: [PokemonType.WATER],
      special: false,
    },
    {
      id: "water4",
      type: CardType.ENERGY,
      name: "Water Energy",
      energyType: PokemonType.WATER,
      provides: [PokemonType.WATER],
      special: false,
    },
    {
      id: "water5",
      type: CardType.ENERGY,
      name: "Water Energy",
      energyType: PokemonType.WATER,
      provides: [PokemonType.WATER],
      special: false,
    },
    {
      id: "water6",
      type: CardType.ENERGY,
      name: "Water Energy",
      energyType: PokemonType.WATER,
      provides: [PokemonType.WATER],
      special: false,
    },
    {
      id: "water7",
      type: CardType.ENERGY,
      name: "Water Energy",
      energyType: PokemonType.WATER,
      provides: [PokemonType.WATER],
      special: false,
    },
    {
      id: "water8",
      type: CardType.ENERGY,
      name: "Water Energy",
      energyType: PokemonType.WATER,
      provides: [PokemonType.WATER],
      special: false,
    },
    {
      id: "water9",
      type: CardType.ENERGY,
      name: "Water Energy",
      energyType: PokemonType.WATER,
      provides: [PokemonType.WATER],
      special: false,
    },
    {
      id: "water10",
      type: CardType.ENERGY,
      name: "Water Energy",
      energyType: PokemonType.WATER,
      provides: [PokemonType.WATER],
      special: false,
    },
    {
      id: "water11",
      type: CardType.ENERGY,
      name: "Water Energy",
      energyType: PokemonType.WATER,
      provides: [PokemonType.WATER],
      special: false,
    },
    {
      id: "water12",
      type: CardType.ENERGY,
      name: "Water Energy",
      energyType: PokemonType.WATER,
      provides: [PokemonType.WATER],
      special: false,
    },
    {
      id: "water13",
      type: CardType.ENERGY,
      name: "Water Energy",
      energyType: PokemonType.WATER,
      provides: [PokemonType.WATER],
      special: false,
    },
    {
      id: "water14",
      type: CardType.ENERGY,
      name: "Water Energy",
      energyType: PokemonType.WATER,
      provides: [PokemonType.WATER],
      special: false,
    },
    {
      id: "double1",
      type: CardType.ENERGY,
      name: "Double Colorless Energy",
      energyType: PokemonType.COLORLESS,
      provides: [PokemonType.COLORLESS, PokemonType.COLORLESS],
      special: true,
    },
    {
      id: "double2",
      type: CardType.ENERGY,
      name: "Double Colorless Energy",
      energyType: PokemonType.COLORLESS,
      provides: [PokemonType.COLORLESS, PokemonType.COLORLESS],
      special: true,
    },
  ]
}

// Generate a fire-focused deck
export function getFireDeck() {
  return [
    // Pokémon Cards
    {
      id: "char1",
      type: CardType.POKEMON,
      name: "Charmander",
      hp: 50,
      stage: "Basic",
      pokemonType: PokemonType.FIRE,
      weakness: PokemonType.WATER,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Scratch",
          damage: 10,
          energyCost: [PokemonType.COLORLESS],
          effect: null,
        },
        {
          name: "Ember",
          damage: 30,
          energyCost: [PokemonType.FIRE, PokemonType.COLORLESS],
          effect: "Discard 1 Fire Energy card attached to this Pokémon.",
        },
      ],
    },
    {
      id: "char2",
      type: CardType.POKEMON,
      name: "Charmander",
      hp: 50,
      stage: "Basic",
      pokemonType: PokemonType.FIRE,
      weakness: PokemonType.WATER,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Scratch",
          damage: 10,
          energyCost: [PokemonType.COLORLESS],
          effect: null,
        },
        {
          name: "Ember",
          damage: 30,
          energyCost: [PokemonType.FIRE, PokemonType.COLORLESS],
          effect: "Discard 1 Fire Energy card attached to this Pokémon.",
        },
      ],
    },
    {
      id: "char3",
      type: CardType.POKEMON,
      name: "Charmander",
      hp: 50,
      stage: "Basic",
      pokemonType: PokemonType.FIRE,
      weakness: PokemonType.WATER,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Scratch",
          damage: 10,
          energyCost: [PokemonType.COLORLESS],
          effect: null,
        },
        {
          name: "Ember",
          damage: 30,
          energyCost: [PokemonType.FIRE, PokemonType.COLORLESS],
          effect: "Discard 1 Fire Energy card attached to this Pokémon.",
        },
      ],
    },
    {
      id: "char4",
      type: CardType.POKEMON,
      name: "Charmander",
      hp: 50,
      stage: "Basic",
      pokemonType: PokemonType.FIRE,
      weakness: PokemonType.WATER,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Scratch",
          damage: 10,
          energyCost: [PokemonType.COLORLESS],
          effect: null,
        },
        {
          name: "Ember",
          damage: 30,
          energyCost: [PokemonType.FIRE, PokemonType.COLORLESS],
          effect: "Discard 1 Fire Energy card attached to this Pokémon.",
        },
      ],
    },
    {
      id: "char5",
      type: CardType.POKEMON,
      name: "Charmeleon",
      hp: 80,
      stage: "Stage 1",
      evolvesFrom: "Charmander",
      pokemonType: PokemonType.FIRE,
      weakness: PokemonType.WATER,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Slash",
          damage: 30,
          energyCost: [PokemonType.COLORLESS, PokemonType.COLORLESS],
          effect: null,
        },
        {
          name: "Flamethrower",
          damage: 50,
          energyCost: [PokemonType.FIRE, PokemonType.FIRE, PokemonType.COLORLESS],
          effect: "Discard 1 Fire Energy card attached to this Pokémon.",
        },
      ],
    },
    {
      id: "char6",
      type: CardType.POKEMON,
      name: "Charmeleon",
      hp: 80,
      stage: "Stage 1",
      evolvesFrom: "Charmander",
      pokemonType: PokemonType.FIRE,
      weakness: PokemonType.WATER,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Slash",
          damage: 30,
          energyCost: [PokemonType.COLORLESS, PokemonType.COLORLESS],
          effect: null,
        },
        {
          name: "Flamethrower",
          damage: 50,
          energyCost: [PokemonType.FIRE, PokemonType.FIRE, PokemonType.COLORLESS],
          effect: "Discard 1 Fire Energy card attached to this Pokémon.",
        },
      ],
    },
    {
      id: "char7",
      type: CardType.POKEMON,
      name: "Charizard",
      hp: 120,
      stage: "Stage 2",
      evolvesFrom: "Charmeleon",
      pokemonType: PokemonType.FIRE,
      weakness: PokemonType.WATER,
      resistance: PokemonType.FIGHTING,
      retreatCost: 3,
      ability: {
        name: "Energy Burn",
        effect:
          "As often as you like during your turn, you may turn all Energy attached to Charizard into Fire Energy.",
      },
      attacks: [
        {
          name: "Fire Spin",
          damage: 100,
          energyCost: [PokemonType.FIRE, PokemonType.FIRE, PokemonType.FIRE, PokemonType.FIRE],
          effect: "Discard 2 Energy cards attached to this Pokémon.",
        },
      ],
    },
    {
      id: "growl1",
      type: CardType.POKEMON,
      name: "Growlithe",
      hp: 60,
      stage: "Basic",
      pokemonType: PokemonType.FIRE,
      weakness: PokemonType.WATER,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Flare",
          damage: 20,
          energyCost: [PokemonType.FIRE, PokemonType.COLORLESS],
          effect: null,
        },
      ],
    },
    {
      id: "growl2",
      type: CardType.POKEMON,
      name: "Growlithe",
      hp: 60,
      stage: "Basic",
      pokemonType: PokemonType.FIRE,
      weakness: PokemonType.WATER,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Flare",
          damage: 20,
          energyCost: [PokemonType.FIRE, PokemonType.COLORLESS],
          effect: null,
        },
      ],
    },
    {
      id: "growl3",
      type: CardType.POKEMON,
      name: "Growlithe",
      hp: 60,
      stage: "Basic",
      pokemonType: PokemonType.FIRE,
      weakness: PokemonType.WATER,
      resistance: null,
      retreatCost: 1,
      attacks: [
        {
          name: "Flare",
          damage: 20,
          energyCost: [PokemonType.FIRE, PokemonType.COLORLESS],
          effect: null,
        },
      ],
    },
    {
      id: "arca1",
      type: CardType.POKEMON,
      name: "Arcanine",
      hp: 100,
      stage: "Stage 1",
      evolvesFrom: "Growlithe",
      pokemonType: PokemonType.FIRE,
      weakness: PokemonType.WATER,
      resistance: null,
      retreatCost: 2,
      attacks: [
        {
          name: "Flamethrower",
          damage: 50,
          energyCost: [PokemonType.FIRE, PokemonType.FIRE, PokemonType.COLORLESS],
          effect: "Discard 1 Fire Energy card attached to this Pokémon.",
        },
        {
          name: "Take Down",
          damage: 80,
          energyCost: [PokemonType.FIRE, PokemonType.FIRE, PokemonType.COLORLESS, PokemonType.COLORLESS],
          effect: "This Pokémon does 20 damage to itself.",
        },
      ],
    },
    {
      id: "arca2",
      type: CardType.POKEMON,
      name: "Arcanine",
      hp: 100,
      stage: "Stage 1",
      evolvesFrom: "Growlithe",
      pokemonType: PokemonType.FIRE,
      weakness: PokemonType.WATER,
      resistance: null,
      retreatCost: 2,
      attacks: [
        {
          name: "Flamethrower",
          damage: 50,
          energyCost: [PokemonType.FIRE, PokemonType.FIRE, PokemonType.COLORLESS],
          effect: "Discard 1 Fire Energy card attached to this Pokémon.",
        },
        {
          name: "Take Down",
          damage: 80,
          energyCost: [PokemonType.FIRE, PokemonType.FIRE, PokemonType.COLORLESS, PokemonType.COLORLESS],
          effect: "This Pokémon does 20 damage to itself.",
        },
      ],
    },

    // Trainer Cards
    {
      id: "prof1",
      type: CardType.TRAINER,
      name: "Professor Oak",
      subtype: TrainerSubtype.SUPPORTER,
      effect: "Discard your hand and draw 7 cards.",
    },
    {
      id: "prof2",
      type: CardType.TRAINER,
      name: "Professor Oak",
      subtype: TrainerSubtype.SUPPORTER,
      effect: "Discard your hand and draw 7 cards.",
    },
    {
      id: "bill1",
      type: CardType.TRAINER,
      name: "Bill",
      subtype: TrainerSubtype.SUPPORTER,
      effect: "Draw 2 cards.",
    },
    {
      id: "bill2",
      type: CardType.TRAINER,
      name: "Bill",
      subtype: TrainerSubtype.SUPPORTER,
      effect: "Draw 2 cards.",
    },
    {
      id: "bill3",
      type: CardType.TRAINER,
      name: "Bill",
      subtype: TrainerSubtype.SUPPORTER,
      effect: "Draw 2 cards.",
    },
    {
      id: "energy1",
      type: CardType.TRAINER,
      name: "Energy Retrieval",
      subtype: TrainerSubtype.ITEM,
      effect: "Put 2 basic Energy cards from your discard pile into your hand.",
    },
    {
      id: "energy2",
      type: CardType.TRAINER,
      name: "Energy Retrieval",
      subtype: TrainerSubtype.ITEM,
      effect: "Put 2 basic Energy cards from your discard pile into your hand.",
    },
    {
      id: "potion1",
      type: CardType.TRAINER,
      name: "Potion",
      subtype: TrainerSubtype.ITEM,
      effect: "Remove 2 damage counters from 1 of your Pokémon.",
    },
    {
      id: "potion2",
      type: CardType.TRAINER,
      name: "Potion",
      subtype: TrainerSubtype.ITEM,
      effect: "Remove 2 damage counters from 1 of your Pokémon.",
    },
    {
      id: "switch1",
      type: CardType.TRAINER,
      name: "Switch",
      subtype: TrainerSubtype.ITEM,
      effect: "Switch your Active Pokémon with 1 of your Benched Pokémon.",
    },
    {
      id: "switch2",
      type: CardType.TRAINER,
      name: "Switch",
      subtype: TrainerSubtype.ITEM,
      effect: "Switch your Active Pokémon with 1 of your Benched Pokémon.",
    },

    // Energy Cards
    {
      id: "fire1",
      type: CardType.ENERGY,
      name: "Fire Energy",
      energyType: PokemonType.FIRE,
      provides: [PokemonType.FIRE],
      special: false,
    },
    {
      id: "fire2",
      type: CardType.ENERGY,
      name: "Fire Energy",
      energyType: PokemonType.FIRE,
      provides: [PokemonType.FIRE],
      special: false,
    },
    {
      id: "fire3",
      type: CardType.ENERGY,
      name: "Fire Energy",
      energyType: PokemonType.FIRE,
      provides: [PokemonType.FIRE],
      special: false,
    },
    {
      id: "fire4",
      type: CardType.ENERGY,
      name: "Fire Energy",
      energyType: PokemonType.FIRE,
      provides: [PokemonType.FIRE],
      special: false,
    },
    {
      id: "fire5",
      type: CardType.ENERGY,
      name: "Fire Energy",
      energyType: PokemonType.FIRE,
      provides: [PokemonType.FIRE],
      special: false,
    },
    {
      id: "fire6",
      type: CardType.ENERGY,
      name: "Fire Energy",
      energyType: PokemonType.FIRE,
      provides: [PokemonType.FIRE],
      special: false,
    },
    {
      id: "fire7",
      type: CardType.ENERGY,
      name: "Fire Energy",
      energyType: PokemonType.FIRE,
      provides: [PokemonType.FIRE],
      special: false,
    },
    {
      id: "fire8",
      type: CardType.ENERGY,
      name: "Fire Energy",
      energyType: PokemonType.FIRE,
      provides: [PokemonType.FIRE],
      special: false,
    },
    {
      id: "fire9",
      type: CardType.ENERGY,
      name: "Fire Energy",
      energyType: PokemonType.FIRE,
      provides: [PokemonType.FIRE],
      special: false,
    },
    {
      id: "fire10",
      type: CardType.ENERGY,
      name: "Fire Energy",
      energyType: PokemonType.FIRE,
      provides: [PokemonType.FIRE],
      special: false,
    },
    {
      id: "fire11",
      type: CardType.ENERGY,
      name: "Fire Energy",
      energyType: PokemonType.FIRE,
      provides: [PokemonType.FIRE],
      special: false,
    },
    {
      id: "fire12",
      type: CardType.ENERGY,
      name: "Fire Energy",
      energyType: PokemonType.FIRE,
      provides: [PokemonType.FIRE],
      special: false,
    },
    {
      id: "fire13",
      type: CardType.ENERGY,
      name: "Fire Energy",
      energyType: PokemonType.FIRE,
      provides: [PokemonType.FIRE],
      special: false,
    },
    {
      id: "fire14",
      type: CardType.ENERGY,
      name: "Fire Energy",
      energyType: PokemonType.FIRE,
      provides: [PokemonType.FIRE],
      special: false,
    },
    {
      id: "double1",
      type: CardType.ENERGY,
      name: "Double Colorless Energy",
      energyType: PokemonType.COLORLESS,
      provides: [PokemonType.COLORLESS, PokemonType.COLORLESS],
      special: true,
    },
    {
      id: "double2",
      type: CardType.ENERGY,
      name: "Double Colorless Energy",
      energyType: PokemonType.COLORLESS,
      provides: [PokemonType.COLORLESS, PokemonType.COLORLESS],
      special: true,
    },
  ]
}
